version: '3.1'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:9000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: "npm run start"